### ISSUE TITLE
Erreur récurrente côté Jeedom

### ISSUE THREAD

**Issue by darghorn** [prysme01/MMM-Jeedom#1]
Bonjour,

J'ai une erreur recurrente côté Jeedom lors de l'accès aux données via le mirroir.

`[Sun Jan 14 12:47:51.842665 2018] [:error] [pid 4162] [client X.X.X.X:45108] PHP Notice:  Undefined index: options in /var/www/html/core/api/jeeApi.php on line 569`
`[Sun Jan 14 12:49:31.849006 2018] [:error] [pid 11780] [client X.X.X.X:51230] PHP Notice:  Undefined index: options in /var/www/html/core/api/jeeApi.php on line 569`

Une petit idée d'où cela pourrait venir ?

Pour l'instant côté miroir je n'ai que cela de déclaré 

`                {`
`                        module: 'MMM-Jeedom',`
 `                       header: 'Maison',`
  `                      position: "top_left",`
   `                     config: {`
    `                            updateInterval: 100000,`
     `                           jeedomAPIKey: "XXX",`
      `                          jeedomURL: "XXXX.jeedom.com",`
       `                         jeedomPORT: "443",`
        `                        jeedomAPIPath: "/core/api/jeeApi.php",`
         `                       sensors: [`
          `                      {`
           `                             idx: "336",`
            `                            symbol: "fa fa-bolt",`
             `                           customTitle: "Consommation   :",`
              `                          unit : "W",`
               `                 },`

**Comment by prysme01** [comment]
Salut,

Sans plus d'information, je dirai que l'idx:336 n'existe pas dans ton jeedom, et du coup jeedom te renvoi undefined index.

**Comment by prysme01** [comment]
Est ce que tu peux valider que l'index existe bien avec cette commande

curl -H "Content-Type: application/json" -X POST -d '{"jsonrpc": "2.0", "id": "1000", "method": "cmd::execCmd", "params": {"apikey": xxxxxxxxxxx"id": 336}}' https://xxxxx/core/api/jeeApi.php | python -m json.tool

{
    "id": "1000",
    "jsonrpc": "2.0",
    "result": {
        "collectDate": "2018-01-15 09:42:35",
        "value": 8.15
    }
}

**Comment by darghorn** [comment]
Hello,
Alors je ne l'avais pas précisé, mais en fait la valeur est correctement remontée sur le miroir, je vois la consommation s'afficher. J'ai cette erreur à chaque interrogation dans jeedom, mais à part ça tout fonctionne.

Pour la commande j'ai le retour suivant :

% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   219  100   109  100   110    860    868 --:--:-- --:--:-- --:--:--   873
{
    "error": {
        "code": 1,
        "message": "Requ\u00eate invalide. Version Jsonrpc invalide : "
    },
    "id": null,
    "jsonrpc": "2.0"
}

**Comment by prysme01** [comment]
Tu as toujours ces messages ? moi sur mon installation jeedom dédié je n'ai pas ces logs

**Comment by darghorn** [comment]
Je n'ai plus rien depuis deux jours, du coup je ferme le ticket. 
Merci pour ton aide :)
