### ISSUE TITLE
error MYSQL

### ISSUE THREAD

**Issue by chassain** [prysme01/MMM-Jeedom#10]
Bonsoir prysme,

Comme dit sur le forum de magicmirror j'ai tenté d'installer jeedom sur un de mes raspberry pi4 en parallèle de magicmirror. J'ai utilisé le pluggin waze et j'ai des résultats sur le site de jeedom mais rien sur le mirroir. En regardant plus attentivement l'installation sur le rasp j'avais une erreur à la dernière étape 

ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
C\033[1;31mNe peut exécuter CREATE USER 'jeedom'@'localhost' IDENTIFIED BY '53e17116c8bb7fa'; dans MySQL - Annulation\033[0;39m

Du coup quand je lance la console sur le magic j'ai une erreur 'moment' (je ne sais pas si c'est lié) mais j'ai bien fait l'installe de npm dans le bon dossier..

Au cas où tu as le temps, je ne suis pas pressé avec les fêtes de fin d'année mais je suis assez curieux de tester ton module et jeedom que je ne connais pas du tout.

De bonnes fêtes en tout cas

**Comment by chassain** [comment]
pb MySQL réglé...j'ai repris l'installation mais toujours pb sur console magic..rien ne s'affiche

Uncaught ReferenceError: moment is not defined
    at Class.start (MMM-Jeedom.js:39)
    at startModules (loader.js:55)
    at loader.js:40
    at HTMLLinkElement.stylesheet.onload (loader.js:200)

Cordialement

**Comment by chassain** [comment]
resolved !!!

add to the MMM-Jeedom.js, the getScripts function below

	getStyles: function() {
	    return ['font-awesome.css'];
	},
        getScripts: function() {                    //
            return ["moment.js"]                  //
        },

**Comment by prysme01** [comment]
Merci, je n'ai pas teste sur les dernieres version de MM ils ont du rajouter ce prerequis.
