### ISSUE TITLE
Hidding a double value equipement

### ISSUE THREAD

**Issue by ArnoStrasbourg** [prysme01/MMM-Jeedom#12]
Hi,

I have a very special ask/interrogation.
I have a binary virtual to force the bathroom heater. So, in my MM I can hide it when the heater is off and show it when on.
But ! in this equipement, I also have a counter, because the switch has a tempo of 30mn and I want to know the state :

![image](https://user-images.githubusercontent.com/6398055/82804589-d71a8d00-9e82-11ea-99d9-a0136f87be5a.png)

Here is my virtual :
![image](https://user-images.githubusercontent.com/6398055/82804685-00d3b400-9e83-11ea-9916-82d286a1200b.png)

On the MM I would like to show "Chauffage forcé" IF it's the case and if it is showed, on the same line, the timer. 
I don't think it is possible with a non-boolean value in the config. But if I put a "boolean: true, the timer disappear.

Do you see a solution or a way to do it ?

Thank you.

Here is my config

`{//` --------------  Widget Forçage SdB  -------------------
	//first info (value and unit only)
	idx: "3771", // affichage du compteur
	sameLine1: true,
	unit: "min",
},
{//second info (title, symbol, value and unit)
	idx: "3580", // affichage état forçage
	sameLine2: true,
        symbol: "free-code-camp",
	customTitle: "Chauffage SdB forcé",
},`

**Comment by prysme01** [comment]
Hi, 

Maybe the easyiest way to do it is to create on JEEDOM side a new virtual that can show what you need to display, I dont want to complexify the plugin on MM to deal with special cases, Jeedom is better at this job. plugin is quite simple, boolean or string that's it.

**Comment by ArnoStrasbourg** [comment]
Ok, I understand. I don't see how I can do differently on Jeedom side, but in any case, thank you for the quick answer

**Comment by prysme01** [comment]
Maybe you can prepare a string in a new virtual in jeedom to display : chauffage force + timer and else OFF

**Comment by ArnoStrasbourg** [comment]
I do the job with a scenario, so it is very easy to activate/desactivate or make visible/invisible the equipement. But unfortunatly, it doesn't disappear in MM-jeedom.
But it's ok, as you said, don't make it too complicated. Options who are implemented works perfectly.
I will do in an other way with the existing options.
Thank you very much.
