### ISSUE TITLE
Update for future 4.2 Jeedom version

### ISSUE THREAD

**Issue by arcameca** [prysme01/MMM-Jeedom#13]
Good day,

First many thanks for this fantastic module who is working verry well. 

Jeedom is currently working on a 4.2 release who is currently in beta. In this version there is a major security update of the API.
https://doc.jeedom.com/fr_FR/core/4.2/changelog

Is there  a chance to see an update of this module to be able to continue using it?

Thank-you.

**Comment by Aldarande** [comment]
It may have a problem but for the moment, it should be work. We could be optimist !

**Comment by Aldarande** [comment]
Hi,

Just fir information, i have try 4.2 andd it still working.

Regards,

**Comment by arcameca** [comment]
Thanks for the info Aldarande.
