### ISSUE TITLE
MagicMirror affiche "Loading" mais rien ne s'affiche

### ISSUE THREAD

**Issue by supermenteur** [prysme01/MMM-Jeedom#16]
Bonjour,

Je pense que ma configuration est bonne mais malgre cela, rien d'apparait, juste "Loading"

                {
                module: 'MMM-Jeedom',
                header: 'Jeedom Maison',
                position: "top_left",
                config: {
                        updateInterval: 3000,
                        jeedomAPIKey: "API jeedom globale",
                        jeedomURL: "192.168.1.102",
                        jeedomPORT: 80,
                        jeedomAPIPath: "/core/api/jeeApi.php",
                        sensors: [
                                {
                                        idx: 12669,
                                        symbol: "fa fa-bolt",
                                        customTitle: "Consommation Jour",
                                        unit : "kWh",
                                },
                        ],
                        }
                },

Bien sur derniere version de MagicMirror, MMM-Jeedom et Jeddom 4.2.16
http://192.168.1.102/core/api/jeeApi.php?apikey=xxxx&type=cmd&id=12669 revoit bien une valeur
Merci d'avance si il y a quelque chose d'incohenrent.

Patrice

**Comment by supermenteur** [comment]
Non rien pour l’instant. Je regarde cote Jeedom si je vois des erreur dans les logs, mais rien.

De : sly83910 ***@***.***>
Envoyé : mercredi 25 mai 2022 17:33
À : prysme01/MMM-Jeedom ***@***.***>
Cc : Patrice Payen ***@***.***>; Author ***@***.***>
Objet : Re: [prysme01/MMM-Jeedom] MagicMirror affiche "Loading" mais rien ne s'affiche (Issue #16)


Bonjour,

J'ai exactement la même problématique que toi.
As tu solutionné ton problème par un autre biais?

Merci

**Comment by mickael067** [comment]
Bonjour,

Il manque l'option de connexion:
`jeedomHTTPS: false`

Dans le code, la valeur par default est :
`jeedomHTTPS: true`

J'espère vous avoir aider.

Bonne journée

**Comment by sly83910** [comment]
Bonjour, 
Perso j'ai bien le JeedomHTTPS: false. 

As t-on moyen de voir les logs du module afin de déterminer le problème?

Merci

**Comment by prysme01** [comment]
Est ce que tu peux essayer avec la clef d'api
