### ISSUE TITLE
moment is not defined when launch

### ISSUE THREAD

**Issue by guillaumesoul** [prysme01/MMM-Jeedom#2]
Hi, 

I installed the module but when launch, I have the following errors : 
-  "moment is not defined" MMM-jeedom.js l29.
- cannot read property getElementsByClassName if null in main.js l134

Any ideas where this come from?

**Comment by prysme01** [comment]
Hi
try to do npm install in /home/pi/MagicMirror/vendor
Moment is not installed on your system.
