### ISSUE TITLE
Problème Affichage Module Jeedom

### ISSUE THREAD

**Issue by chipie2rc** [prysme01/MMM-Jeedom#7]
Bonsoir,
J'ai découvert ce module pour le faire fonctionner avec MagicMirror que vous avez réalisé.
Je l'ai configuré et il fonctionne parfaitement.
Voilà ma Copie de mon écran:

[IMG]https://imagizer.imageshack.com/v2/xq90/924/Ody3zX.jpg[/IMG][/URL]

Le seul problème est que le "symbole tension", "Consommation Maison" et le " nombre de watt "est touche à touche sur l' écran contrairement à ce que l'on peut voir sur la capture écran suivante du module décrivant votre module. Sur la capture il y a des espaces entre "symbole tension " , "Consommation Maison " et " Nombre Watt". 
[https://raw.githubusercontent.com/prysme01/MMM-Jeedom/master/screenshots/MMM-Jeedom.png](url)
Comme résoudre ce problème d'affichage?
Merci pour votre aide

**Comment by chipie2rc** [comment]
Désolé je reformule ma demande car mes captures d'écran ne s'affiche pas normalement.
Bonsoir,
J'ai découvert ce module pour le faire fonctionner avec MagicMirror que vous avez réalisé.
Je l'ai configuré et il fonctionne parfaitement.
Voilà ma Copie de mon écran:

<a target="_blank" href="https://imageshack.com/i/plVmbnxtj"><img src="https://imagizer.imageshack.com/v2/xq90/921/Vmbnxt.jpg" border="0"></a>

Le seul problème est que le "symbole tension", "Consommation Maison" et le " nombre de watt "est touche à touche. De même qu'entre le symbole température et extérieur et garage etc..
Contrairement à votre capture d'écran  décrivant votre module ou l'on voit qu' il y a des espaces entre "symbole tension " , "Consommation Maison " et " Nombre Watt" et entre symbole température et Température Rez de chaussée, etc...

<a target="_blank" href="https://imageshack.com/i/pn7L0XmAp"><img src="https://imagizer.imageshack.com/v2/xq90/923/7L0XmA.png" border="0"></a>

**Comment by prysme01** [comment]
Je vois, mais en fait c'est Magic Mirror qui gere la taille de la colonne, elle est dynamique en fonction du contenu des differents modules dans la colonne. Du coup chez moi j'ai un autre module en dessous ou au dessus qui est plus large et donc l'affichage s'espace naturellement mieux. Tu devrais regarder du cote de la feuille de style de magic mirror pour y ajouter un width plus large.
Ca se passe dans ce fichier
https://github.com/MichMich/MagicMirror/blob/master/css/custom.css

**Comment by prysme01** [comment]
sinon tu peux aussi modifier la fonction getDom dans ce fichier de mon module https://github.com/prysme01/MMM-Jeedom/blob/master/MMM-Jeedom.js

C'est ici que l'on cree les elements, il suffit de rajouter autant d'espace que tu le souhaites entre l'icon et le texte.

**Comment by chipie2rc** [comment]
Bonsoir,
Merci beaucoup, je vais essayer cela ce soir.

**Comment by chipie2rc** [comment]
Rebonsoir,
J'ai bien regardé votre fichier à l'aide d'un éditeur au niveau du getDom mais à quel niveau il faut rajouter des espaces entre l'icone et le texte.
Malheureusement je suis un bleu en matière de code.
Merci d'avance.
